name: supernova
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.3.0
  platform_info: ^4.0.2
  system_info2: ^4.0.0
  awesome_snackbar_content: ^0.1.3
  lottie: ^2.7.0
  network_info_plus: ^4.1.0
  dart_ipify: ^1.1.1
  battery_plus: ^4.1.0
  responsive_sizer: ^3.2.0
  icons_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lotties/